<?php return array (
  'site_title' => 'Bug Finder',
  'base_color' => '#d09f06',
  'secondary_color' => '#f0b90b',
  'time_zone' => 'UTC',
  'force_ssl' => '0',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'base_currency_rate' => 1.0,
  'theme' => 'peerToPeer',
  'fraction_number' => 0,
  'paginate' => 20,
  'tradeCharge' => 5,
  'trade_extra_time' => 10,
  'incompleteLimit' => 5,
  'ad_rate_update' => 1,
  'email_verification' => 0,
  'email_notification' => 1,
  'sms_verification' => 1,
  'sms_notification' => 0,
  'push_notification' => 0,
  'error_log' => 0,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 1,
  'bonus_amount' => '20',
  'joining_bonus' => 1,
  'sender_email' => 'support@mail.com',
  'sender_email_name' => 'Bug Finder',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'sandbox.smtp.mailtrap.io',
    'smtp_port' => '2525',
    'smtp_encryption' => 'tls',
    'smtp_username' => '6bb1868e62d487',
    'smtp_password' => '0609b9e11bbbd6',
  ),
  'fiat_currency_api' => 'WXLRMqWaBZeZZ5c1qSV52eHVeyQVY7VW',
  'fiat_currency_status' => 1,
  'crypto_currency_api' => '1df68913f43debee2bca1bb8fd3b570de123f86dfe86cee17398270d1c6eac35',
  'crypto_currency_status' => 0,
);